---
  - name: Ensure AD account GohanADM exists
    win_domain_user:
      name: gohan.adm
      firstname: GohanADM
      password: PassW0rd876#!
      state: present
      groups:
        - Domain Users

  - name: Ensure AD account Vegetaadm exists
    win_domain_user:
      name: vegeta.adm
      firstname: VegetaADM
      password: PassW0rd765#!
      state: present
      groups:
        - Domain Users

  - name: Ensure AD account TrunksADM exists
    win_domain_user:
      name: trunks.adm
      firstname: TrunksADM
      password: PassW0rd654#!
      state: present
      groups:
        - Domain Users

  - name: Ensure AD account serveradmin exists
    win_domain_user:
      name: server.admin
      firstname: ServerAdmin
      password: P@ssW0rd432!
      state: present
      groups:
        - Domain Admins
