---
  - name: Enable Remote Desktop
    raw: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f

  - name: Make sure admin user is set
    win_user:
     name: Administrator
     password: PassW0rd432!
     state: present
     groups:
      - Administrators

  - name: Install Active Directory Services
    win_feature: >
      name=AD-Domain-Services
      include_management_tools=yes
      include_sub_features=yes
      state=present

  - name: Ensure the domain exists
    win_domain:
      dns_domain_name: capsulecorp.local
      domain_mode: WinThreshold
      forest_mode: WinThreshold
      safe_mode_password: PassW0rd432!
    register: domain_create

  - name: Reboot server after domain install
    win_reboot:
      test_command: 'exit (Get-Service -Name LanmanServer).Status -ne "Running"'
    when: domain_create.reboot_required
  
  - name: Wait for domain controller to be ready
    win_shell: |
      Get-ADDomain -Server "capsulecorp.local"
    register: dc_ready
    until: dc_ready is not failed
    ignore_errors: yes
    retries: 60
    delay: 15

  - name: Promote goku to domain controller
    win_domain_controller:
      dns_domain_name: capsulecorp.local
      safe_mode_password: PassW0rd432!
      domain_admin_password: PassW0rd432!
      domain_admin_user: "capsulecorp.local\\goku"
      state: domain_controller
    register: dc_create

  - name: Reboot after dc promotion
    win_reboot:
      test_command: 'exit (Get-Service -Name LanmanServer).Status -ne "Running"'
    when: dc_create.reboot_required


  - name: Set DA user account information
    win_domain_user:
      name: goku
      firstname: Goku
      password: PassW0rd432!
      state: present
      groups:
        - Domain Admins

  - include: accounts.yml

