---
# Load required powershell modules
- name: Powershell | Check for SQLServer DSC Powershell module
  win_psmodule:
    name: SQLServerDsc
    state: present
    accept_license: true

- name: Powershell | Check for Storage DSC Powershell module
  win_psmodule:
    name: StorageDsc
    state: present
    accept_license: true

- name: Powershell | Check for ServerManager Powershell module
  win_psmodule:
    name: ServerManager
    state: present
    accept_license: true

- name: Powershell | Ensure that DBA Tools module is present
  win_psmodule:
    name: dbatools
    state: present
    accept_license: true

- name: Powershell | Check for xNetworking Powershell module
  win_psmodule:
    name: xNetworking
    state: present
    accept_license: true
  register: powershell_modules

- include: pre_reqs.yml
  when: powershell_modules.changed

- include: accounts.yml
- include: prepare_install.yml
- include: install.yml
- include: firewall.yml
- include: configure.yml
