---
- name: Add RVM GPG keys
  become: true
  shell: |
    gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

- name: Pull down RVM and install with latest stable
  become: true
  shell: |
    \curl -sSL https://get.rvm.io | sudo bash -s stable --ruby

- name: Add RVM bin path to $PATH
  become: true
  copy:
    dest: /etc/profile.d/rvm-path.sh
    content: 'PATH=$PATH:/usr/local/rvm/rubies/ruby-2.7.0/bin'

- name: Add pentest to the RVM group
  become: true
  shell: |
    usermod -a -G rvm pentest

- name: Source the rvm-path.sh file
  shell: bash -cl "source /etc/profile.d/rvm-path.sh"
