---
  - name: Disable windows defender sending sample
    win_shell: Set-MpPreference -MAPSReporting 0

  - name: Disable windows defender sending sample #2 : never send
    win_shell: Set-MpPreference -SubmitSamplesConsent 2

  - name: Disable network drive scanning
    win_shell: Set-MpPreference -DisableScanningMappedNetworkDrivesForFullScan $true

  - name: Disable realtime monitoring
    win_shell: Set-MpPreference -DisableRealtimeMonitoring $true