---
  - name: Create service folder
    ansible.windows.win_file:
      path: C:\\Program Files\\Vulnerable Service\\
      state: directory

  - name: Upload service file
    ansible.windows.win_copy:
      src: "files/service.exe"
      dest: "C:\\Program Files\\Vulnerable Service\\service.exe"

  - name: Create a service
    win_shell: New-Service -Name "VulnService" -DisplayName "Vulnerable Service" -Description "This is a vulnerable service."  -BinaryPathName "C:\Program Files\Vulnerable Service\service.exe" -StartupType Auto
        
  - name: Modify write permissions of vulnerable service folder
    ansible.windows.win_acl:
      path: C:\\Program Files\\Vulnerable Service\\
      user: Users
      rights: Read,Write,Modify,FullControl,Delete
      type: allow

